### ISSUE TITLE
Getting Error 404 when plugin tries to log in

### ISSUE THREAD

**Issue by gintonic4all** [adhyh/homebridge-vwconnectid#1]
**Describe Your Problem:**
Log in to VW We Connect iD does not work. Homebridge log reports error 404.
**Logs:**
ERROR: Failed in receive login url 
ERROR: 404
ERROR: "404 Not Found: Requested route ('login.apps.emea.vwapps.io') does not exist.\n"
ERROR: Failed in first login step 
ERROR: 404
ERROR: "404 Not Found: Requested route ('login.apps.emea.vwapps.io') does not exist.\n"
ERROR: Login Failed

**Plugin Config:**

   "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "iD.4",
            "platform": "WeConnectID",
            "weconnect": {
                "username": "xyz@uvw.com",
                "password": "mypasswdxyz",
                "vin": "myvinMan"
            },
            "options": {
                "chargingAccessory": "Charging",
                "climatisationAccessory": "Climatisation",
                "locationMotionSensors": [
                    {
                        "name": "Home",
                        "lat": 60,
                        "lon": 40,
                        "radius": 100
                    },
                    {
                        "name": "Work",
                        "lat": 40,
                        "lon": 2,
                        "radius": 100
                    }
                ],
                "eventMotionSensors": [
                    {
                        "name": "notSafeCar",
                        "event": "statusNotSafe"
                    }
                ]
            }
        }

**Screenshots:**
-

**Environment:**

* **Plugin Version**: v1.0.1
* **Homebridge Version**: v1.6.0
* **Node.js Version**: v18.14.2
* **NPM Version**: 9.5.1
* **Operating System**: Raspbian /hb-service

**Comment by adhyh** [comment]
Looks like a problem at the server side (VW). I will dive into this a bit more later.
