### ISSUE TITLE
Skoda Connect

### ISSUE THREAD

**Issue by django52** [adhyh/homebridge-vwconnectid#12]
Is there a chance that you can build a skoda connect Plugin for homebridge?

**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by adhyh** [comment]
Unfortunately there is quite some id specific code, so building the plugin for Skoda would be too time consuming at the moment.

**Comment by django52** [comment]
Ok thanks.Beste GrüßeLars ***@***.*** 09.09.2023 um 18:05 schrieb Adhy ***@***.***>:﻿
Unfortunately there is quite some id specific code, so building the plugin for Skoda would be too time consuming at the moment.
