### ISSUE TITLE
Error shuts down Homebridge

### ISSUE THREAD

**Issue by frankb-CZ** [adhyh/homebridge-vwconnectid#14]
**Describe The Bug:**
After setting the climatisation type (Heating, cooling, auto) error appears in the logs and home bridge shuts down.

**To Reproduce:**
Set heating mode in the Apple Home

**Expected behavior:**
Not to have Heating mode at all as this is controlled by car automatically based on set and actual temperature. Just to have on off and temperature settings.

**Logs:**

TypeError: Cannot read properties of undefined (reading 'climatisationSettings')
    at /var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:1840:65
    at new Promise (<anonymous>)
    at VwWeConnect.setIdRemote (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:1836:16)
    at /var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:496:18
    at new Promise (<anonymous>)
    at VwWeConnect.setClimatisation (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:477:16)
    at ClimatisationAccessory.setTargetTemperature (/var/lib/homebridge/node_modules/homebridge-vwconnectid/src/climatisationAccessory.ts:65:26)
    at TargetTemperature.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:174:57)

**Plugin Config:**

{
            "name": "ID",
            "platform": "WeConnectID",
            "weconnect": {
                "username": "I have email here",
                "password": "password",
                "vin": "VIN is hère but removed for privacy"
            },
            "options": {
                "logLevel": "NONE",
                "chargingAccessory": "Charging",
                "climatisationAccessory": "Climatisation",
                "remainingRangeAccessory": "Remaining km",
                "destinations": [
                    {
                        "name": "Y",
                        "lat": XYZ,
                        "lon": XYZ,
                        "address": {
                            "country": "XYZ",
                            "street": "XYZ",
                            "zipCode": "XYZ",
                            "city": "XYZ"
                        },
                        "notificationRadius": 300
                    },
                    {
                        "name": "A",
                        "lat": XYZ,
                        "lon": XYZ,
                        "address": {
                            "country": "XYZ",
                            "street": "XYZ",
                            "zipCode": "XYZ",
                            "city": "XYZ"
                        },
                        "notificationRadius": 300
                    },
                    {
                        "name": "B",
                        "lat": XYZ,
                        "lon": XYZ,
                        "address": {
                            "country": "XYZ",
                            "street": "XYZ",
                            "zipCode": "XYZ",
                            "city": "XYZ"
                        },
                        "notificationRadius": 300
                    }
                ],
                "routes": [
                    {}
                ],
                "settingSwitches": [
                    {
                        "name": "Reduced AC",
                        "setting": "reducedAC"
                    },
                    {
                        "name": "Plug Unlock",
                        "setting": "autoUnlockPlug"
                    },
                    {
                        "name": "Climatization at unlock",
                        "setting": "climatizationAtUnlock"
                    },
                    {
                        "name": "Window Heating",
                        "setting": "climatisationWindowHeating"
                    },
                    {
                        "name": "Front Left Zone",
                        "setting": "climatisationFrontLeft"
                    },
                    {
                        "name": "Front Right Zone",
                        "setting": "climatisationFrontRight"
                    }
                ],
                "eventMotionSensors": [
                    {
                        "name": "Car unsafe state",
                        "event": "statusNotSafe"
                    }
                ]
            }

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.1.3
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: hb-service

**Comment by frankb-CZ** [comment]
Another one 

[ID] Set Characteristic On -> false
[19/10/2023, 13:26:39] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".
[19/10/2023, 13:26:39] Got SIGTERM, shutting down Homebridge...

**Comment by adhyh** [comment]
I can't reproduce this error. Are you still getting this?
