### ISSUE TITLE
"The Charging's battery is at 80%"

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#16]
**Is your feature request related to a problem? Please describe:**
when i ask Siri what the battery level of my car is (i've named the HomeKit "room" associated with this plugin "Car"), Siri responds with "The Charging's battery is at XX%"

**Describe the solution you'd like:**
i'd like it if Siri responded with "The Car's battery is at XX%" where "Car" either comes from the room's name or some other configurable value

**Describe alternatives you've considered:**
i tried changing the `chargingAccessory` name to "Car" but that didn't work

**Additional context:**

**Comment by adhyh** [comment]
Changing the chargingAccessory name is the way to go, but you have to manually delete the chargingAccessory accessory from homebridge first for it to be created again with the new name. Doing this I was able to ask Siri for the battery level of the car and she (?) responded with the charging accessory name..

Furthermore I expect that siri's association with the room name may be stronger than with the accessory name, so you may find a conflict when chargingAccessory name and room name are the same. Just give it a try and see...

**Comment by r2shyyou** [comment]
> Changing the chargingAccessory name is the way to go, but you have to manually delete the chargingAccessory accessory from homebridge first for it to be created again with the new name. Doing this I was able to ask Siri for the battery level of the car and she (?) responded with the charging accessory name..
> 
> Furthermore I expect that siri's association with the room name may be stronger than with the accessory name, so you may find a conflict when chargingAccessory name and room name are the same. Just give it a try and see...

thanks! you were right about the conflict between the room name and accessory name. i changed the accessory name to something more relevant to me and now it's better.
