### ISSUE TITLE
My JSON is invalid, if I follow the guide

### ISSUE THREAD

**Issue by kennls** [adhyh/homebridge-vwconnectid#17]
latest version as of today, I have copied the JSON text from here and trying to insert it into my almost empty homebrigde JSON config file (empty as this is will be my only homebrigde plugin.

I get a invalid json file, when I try to save.

It needs to be put into here 

{
    "bridge": {
        "name": "Homebridge XXXX”,
        "username": “XXXXXXXXX,
        "port": 51464,
        "pin": “XXX”-XX-XXXX,
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}

**Comment by r2shyyou** [comment]
> latest version as of today, I have copied the JSON text from here and trying to insert it into my almost empty homebrigde JSON config file (empty as this is will be my only homebrigde plugin.
> 
> 
> 
> I get a invalid json file, when I try to save.
> 
> 
> 
> It needs to be put into here 
> 
> 
> 
> {
> 
>     "bridge": {
> 
>         "name": "Homebridge XXXX”,
> 
>         "username": “XXXXXXXXX,
> 
>         "port": 51464,
> 
>         "pin": “XXX”-XX-XXXX,
> 
>         "advertiser": "bonjour-hap"
> 
>     },
> 
>     "accessories": [],
> 
>     "platforms": [
> 
>         {
> 
>             "name": "Config",
> 
>             "port": 8581,
> 
>             "platform": "config"
> 
>         }
> 
>     ]
> 
> }
> 
> 
> 
> 
> 
> 

there are a couple of issues in the config you posted:

```
{
"bridge": {
"name": "Homebridge XXXX”,
"username": “XXXXXXXXX`"`,
"port": 51464,
"pin": “XXX~~”~~-XX-XXXX`"`,
"advertiser": "bonjour-hap"
},
"accessories": [],
"platforms": [
{
"name": "Config",
"port": 8581,
"platform": "config"
}
]
}
```
i’m on my mobile though so i don't know if the above code will render properly (i've seen it not do so previously)

**Comment by adhyh** [comment]
Yeah, check your quotation marks, as indicated by Arthur. 

Numbers have no quotation marks and all others have one in front and one in the back. 

Also, " is not the same as “. (Looks like you are on an Apple computer). The one to use is "

**Comment by kennls** [comment]
I have tried it on Windows and Mac. Basically I copy your JSON, correct it with my info and put it into Homebrigde json config. No matter how I try to paste the example JSON into it, it gives me an error with invalid JSON. 
<img width="497" alt="Skærmbillede 2023-12-26 kl  22 07 49" src="https://github.com/adhyh/homebridge-vwconnectid/assets/94071295/5c187926-6c1c-419c-b508-d5ef8b3958ba">
<img width="346" alt="Skærmbillede 2023-12-26 kl  22 12 18" src="https://github.com/adhyh/homebridge-vwconnectid/assets/94071295/a55413af-77c6-46de-baf5-e5e94c5d1fc4">

**Comment by kennls** [comment]
<img width="497" alt="Skærmbillede 2023-12-26 kl  22 07 49" src="https://github.com/adhyh/homebridge-vwconnectid/assets/94071295/4b32d9b0-98f2-4231-b648-42714f8eda55">

**Comment by kennls** [comment]
This is the working JSON Config I have tried to edit

<img width="497" alt="Skærmbillede 2023-12-26 kl  22 07 49" src="https://github.com/adhyh/homebridge-vwconnectid/assets/94071295/5db5debc-4dac-4b12-8949-080e3f101de7">

**Comment by kennls** [comment]
<img width="1020" alt="Skærmbillede 2023-12-26 kl  22 17 27" src="https://github.com/adhyh/homebridge-vwconnectid/assets/94071295/09f6aac5-978e-4fc5-a409-1bb3253cc570">
<img width="380" alt="Skærmbillede 2023-12-26 kl  22 18 09" src="https://github.com/adhyh/homebridge-vwconnectid/assets/94071295/d67cf651-8d0b-4497-9818-114c98b873a2">

**Comment by adhyh** [comment]
Try line 14: 
},

**Comment by kennls** [comment]
Basically I'm saying, the instructions don't work. I'm installing it on a newly installed Homebrigde, with no plugins installed.

The instructions of how to insert the "we connect" JSON section into my existing JSON config, is unclear for a guy like me, who never edits a homebrigde config, since I use home assistant and tinker with my home server. I use HA for non HomeKit devices and even have my Viessmann gas heater on HA.

I would love to get your product up and running, but I have tried to insert the code with my user, VIN, gps locations and so on, but it won't save in my homebrigde config. I have been running VWs friend earlier.

I think the problem is, that it is a bit unclear for me, where the JSON section is supposed to go. Is it at the end of the config (doesn't work. Do I insert it under accessories, but again it doesn't work.

Thanks for the help so far.

**Comment by kennls** [comment]
I'm following this guide, and set it in like the blue square....that doesn't work

https://github.com/homebridge/homebridge/wiki/Homebridge-Config-JSON-Explained

**Comment by adhyh** [comment]
ahh, i get it. Take the working config from above, put the closing bracket ], from line 9 on a new line and paste the following **in between** those brackets:
```
    {
            "name": "We Connect ID",
            "platform": "WeConnectID",
            "weconnect": {
                "username": "We Connect username",
                "password": "We Connect password",
                "vin": "VIN OF YOUR CAR"
            },
            "options": {
                "logLevel": "NONE",
                "apiPort": 1234,
                "chargingAccessory": "Charging",
                "climatisationAccessory": "Climatisation",
                "remainingRangeAccessory": "Remaining km",
                "destinations": [
                    {
                        "name": "Home",
                        "lat": 52.123456,
                        "lon": 5.123456,
                        "address": {
                            "country": "Nederland",
                            "street": "My street 4",
                            "zipCode": "1234 AA",
                            "city": "My town"
                        },
                        "notificationRadius": 300
                    },
                    {
                        "name": "Work",
                        "lat": 52.234567,
                        "lon": 4.234567,
                        "address": {
                            "country": "Nederland",
                            "street": "Cool street 75",
                            "zipCode": "2345 BB",
                            "city": "Your city"
                        },
                        "notificationRadius": 200
                    }
                ],
                "settingSwitches": [
                    {
                        "name": "Reduced AC",
                        "setting": "reducedAC"
                    },
                    {
                        "name": "Plug Unlock",
                        "setting": "autoUnlockPlug"
                    },
                    {
                        "name": "Climatization at unlock",
                        "setting": "climatizationAtUnlock"
                    },
                    {
                        "name": "Window Heating",
                        "setting": "climatisationWindowHeating"
                    },
                    {
                        "name": "Front Left Zone",
                        "setting": "climatisationFrontLeft"
                    },
                    {
                        "name": "Front Right Zone",
                        "setting": "climatisationFrontRight"
                    }
                ],
                "eventMotionSensors": [
                    {
                        "name": "Car unsafe state",
                        "event": "statusNotSafe"
                    }
                ]
            }
        }
``` 

so your config as of line 9 looks like:
```
"accessories": [
----->the part of code pasted above
],
"platforms": [
----->etc.

**Comment by adhyh** [comment]
> I'm following this guide, and set it in like the blue square....that doesn't work
> 
> https://github.com/homebridge/homebridge/wiki/Homebridge-Config-JSON-Explained

... And if my suggestion above doesnt work, try to paste the code from the previous post under the platforms section (the purple section in your link)..

**Comment by kennls** [comment]
Thanks for your help so far....your new section works, but now I get a new error from Homebrigde.

<img width="391" alt="Skærmbillede 2023-12-27 kl  10 08 36" src="https://github.com/adhyh/homebridge-vwconnectid/assets/94071295/5de1bf70-03ec-4e3e-80f4-06a213b23bda">
<img width="270" alt="Skærmbillede 2023-12-27 kl  10 10 52" src="https://github.com/adhyh/homebridge-vwconnectid/assets/94071295/3d479d30-bea9-4cad-b16a-15366a816302">

**Comment by adhyh** [comment]
try moving the block (with the redline in the previous post) to the platforms section of the config. So adjust "platforms" line 10~16 to this:
```
"platforms": [
   {
   "name": "Config",
   "port": 8581,
   "platform": "config"
   },
   ---> insert configuration block here. Note the comma on the previous line
]
```

**Comment by kennls** [comment]
Now we are trough the JSON config faults, and Homebrigde have accepted the JSON :)

Now I'm just waiting for the devices to pop up. No errors in loading.
<img width="806" alt="Skærmbillede 2023-12-27 kl  16 45 59" src="https://github.com/adhyh/homebridge-vwconnectid/assets/94071295/8cf221a0-b788-42dd-9c94-49817528b2ca">

**Comment by kennls** [comment]
It works....thanks for your help :)
![Uploading IMG_9081.png…]()

**Comment by adhyh** [comment]
Good to hear you got it working. I will improve the installation instructions with the next update.
