### ISSUE TITLE
Add lock/unlock functionality

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#2]
**Is your feature request related to a problem? Please describe:**

Not related to any actual problem

**Describe the solution you'd like:**

A lock accessory to lock & unlock the vehicle's doors

**Describe alternatives you've considered:**

None

**Comment by adhyh** [comment]
I agree that would be a very useful feature.  Unfortunately the VW backend doesn't support remote (un)locking for the ID series.

**Comment by r2shyyou** [comment]
> I agree that would be a very useful feature.  Unfortunately the VW backend doesn't support remote (un)locking for the ID series. 

@adhyh that's too bad. thanks for responding!
