### ISSUE TITLE
Connexion refused

### ISSUE THREAD

**Issue by Libar19** [adhyh/homebridge-vwconnectid#21]
[Golf GTE] /signin-service/v1/a24fba63-34b3-4d43-b181-942111e6bda8@apps_vw-dilab_com/terms-and-conditions?relayState=4c1013e3e82441f1ce92cedad51ab8d36b5612b3&canChangeCountryOfResidence=false&userId=10398390-1449-49cf-bf7b-a9836b9503ee&updated=dataprivacy
[12/5/2024, 10:19:51 AM] [Golf GTE] No valid userid, please visit this link or logout and login in your app account:
[12/5/2024, 10:19:51 AM] [Golf GTE] https://identity.vwgroup.io/signin-service/v1/a24fba63-34b3-4d43-b181-942111e6bda8@apps_vw-dilab_com/terms-and-conditions?relayState=4c1013e3e82441f1ce92cedad51ab8d36b5612b3&canChangeCountryOfResidence=false&userId=10398390-1449-49cf-bf7b-a9836b9503ee&updated=dataprivacy
[12/5/2024, 10:19:51 AM] [Golf GTE] Try to auto accept new consent
[12/5/2024, 10:19:51 AM] [Golf GTE] Login Failed
[12/5/2024, 10:19:51 AM] [Golf GTE] 
[12/5/2024, 10:19:51 AM] [Golf GTE] {}
[12/5/2024, 10:19:51 AM] [Golf GTE] Failed to auto accept
[12/5/2024, 10:19:51 AM] [Golf GTE] 405

Hello, i have this problem with my plugin. when i go to the link  " Safari cannot open the page because the address is invalid." Do you have an idea ?

thank's in advance

**Comment by adhyh** [comment]
T&C have changed, which you need to accept manually. The link should work (I tried yours and it does open on my browser. This one expired, but if you restart HB and open the new link it should work.

**Comment by r2shyyou** [comment]
there are new terms & conditions that you have to accept. log in via the web, accept them, and then restart the plugin. the error should go away

**Comment by adhyh** [comment]
Looks like a javascript dump. Try opening the link in another browser.

**Comment by Libar19** [comment]
yes, but i have this 
![Uploading Capture d’écran 2024-12-05 à 19.59.43.png…]()

**Comment by Libar19** [comment]
Hello , always this problem .. i don't understand

**Comment by r2shyyou** [comment]
> Hello , always this problem .. i don't understand

did you try in a different browser? or a private browser window? you could try clearing your cache and trying again

**Comment by Libar19** [comment]
I try with SAFARI and CHROME on my different mac (my mac mini with homebridge, my mac book air, my iphone ) i clean the cache of safari and chrome but always the problems

**Comment by r2shyyou** [comment]
> I try with SAFARI and CHROME on my different mac (my mac mini with homebridge, my mac book air, my iphone ) i clean the cache of safari and chrome but always the problems (my iphone redirect to volkswagen app, i try to logout and problem is same)

that's strange indeed. all i can suggest at this point is to start from the main Volkswagen website, and try to login from there. that's what i did, and i was able to accept the new terms & conditions right away.

**Comment by Libar19** [comment]
I already Connect in Volkswagen , we Connect and vwgroup.io. But same problem..

**Comment by Libar19** [comment]
hello , i restart all installation on my mac book air (with node 20) and i have the same problem..

**Comment by adhyh** [comment]
https://github.com/tillsteinbach/WeConnect-cli
You can try this app to connect to the backend. Maybe it works.

**Comment by Libar19** [comment]
i have the same problem with WeConnect-cli ..

**Comment by adhyh** [comment]
try logging in to https://id.vwgroup.io/account and see if you can accept T&C there.

**Comment by Libar19** [comment]
already done. I even deleted everything, reset Carnet in the golf. Delete all authorizations in Volkswagen ID and then put it back and nothing

**Comment by Libar19** [comment]
Hello, having no solution I modified my vw account to say that I reside in the Netherlands (maybe the problem comes from my country ^^) so I reconfigured everything and here is my log in homebridge:

[12/13/2024, 3:08:29 PM] [Golf 7.5 GTE] No Token received. Please try to logout and login in the VW app or select type VWv2 in the settings
how do you set VWv2?

**Comment by r2shyyou** [comment]
> Hello, having no solution I modified my vw account to say that I reside in the Netherlands (maybe the problem comes from my country ^^) so I reconfigured everything and here is my log in homebridge:
> 
> 
> 
> ERROR: No Login Form found for type: Wc
> 
> INFO:  Active VIN successfully set to <my VIN>.
> 
> 
> 
> [12/13/2024, 3:08:29 PM] [Golf 7.5 GTE] No Token received. Please try to logout and login in the VW app or select type VWv2 in the settings
> 
> how do you set VWv2?

what is your country? i noticed that your screenshots are in french

**Comment by Libar19** [comment]
I'm French.;). The plugin work good. I create new account bases netherland.
I have error but works. But I can't add to HomeKit I don't know why..

**Comment by r2shyyou** [comment]
> I'm French.;). The plugin work good. I create new account bases netherland.
> I have error but works. But I can't add to HomeKit I don't know why..

that's very strange, since i'm also in france and didn't have this issue at all. i am, however, using it with an ID.x car, whereas you're using it with a Golf, so perhaps that's causing the issue? ¯\_(ツ)_/¯

**Comment by Libar19** [comment]
it works very well in France too me too. I had to just adjust the plugin and stay on the second version (1.0.3) to have better stability on my golf. I also modified the API for the requests because it crashed the application, but I changed my mac server to a mac m1, and I had to start all over again because I deleted everything ... and since then it doesn't work at all (except a little progress)

**Comment by adhyh** [comment]
You are using the plugin with a Golf, but the plugin uses id.x login and authentication logic and api calls. I understand that it used to work before (which was surprising to me), but maybe something has changed on the backend side. 

You can try to make api calls using https://github.com/nightsha-de/npm-vwconnectapi and see if that works (VWv2). I adjusted that one to have the extra functionality that i required, but removed the non-id specific code. 

Other than that I'm out of ideas.

**Comment by Libar19** [comment]
Golf or ID works the same, the same application, I can use your plugin, but it's at the request level that it blocks (too many requests, the gte must be limited in terms of requests, I downloaded your API locally, modified your plugin so that it uses it locally as well) and upgraded your plugin to version 1.0.3 and it works well, now I'm trying to adjust your latest version plugin for my golf (I deleted everything that was an air conditioning control except the thermostat)

**Comment by Libar19** [comment]
You can close this issue. With an account in Netherlands. All work :). Can I copy your plugin to make plugin for golf GTE ?

**Comment by adhyh** [comment]
Glad you got it working! Yes, of course feel free to make your own version.
