### ISSUE TITLE
Repeated 404 error in log

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#3]
**Describe The Bug:**
While everything seems to function properly (thank you!), I do get the following errors repeatedly in the log:

```
ERROR: TypeError: Cannot read properties of undefined (reading 'data')
ERROR: get id parking position Failed
ERROR: Failed to get token
ERROR: 404
ERROR: "default backend - 404"
ERROR: TypeError: Cannot read properties of undefined (reading 'data')
ERROR: get id parking position Failed
ERROR: Failed to get token
ERROR: 404
ERROR: "default backend - 404"
ERROR: TypeError: Cannot read properties of undefined (reading 'data')
ERROR: get id parking position Failed
ERROR: Failed to get token
ERROR: 404
ERROR: "default backend - 404"
```

**Environment:**

* **Plugin Version**: v1.0.2
* **Homebridge Version**: v1.6.0
* **Node.js Version**: v18.14.2
* **NPM Version**: v9.5.0
* **Operating System**: Raspbian

**Comment by adhyh** [comment]
The backend can indeed be quite chatty. I will look for a more elegant solution later, for now (update 1.0.3) you can add
`"logLevel": "NONE"` to the "options" in the config to keep the backend quiet. logLevel options are NONE, ERROR, INFO, DEBUG.
