### ISSUE TITLE
Add support for battery control

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#4]
**Is your feature request related to a problem? Please describe:**
Currently, I have to ask Siri what the light level of the car is in order for it to respond with "The Battery Level is...". Asking Siri what the current battery level is results in a message that there are no accessories that support battery control.

**Describe the solution you'd like:**
Add battery control service so that Siri can respond with the battery level when asked directly.

**Comment by r2shyyou** [comment]
p.s. you should add a sponsor option ;)

**Comment by adhyh** [comment]
I added a BatteryLevel service to 1.0.3, so you should be able to ask Siri for battery level now. I tested it in Dutch and English.

PS. Thanks for the support ;)

**Comment by r2shyyou** [comment]
@adhyh you're welcome and thanks for the addition and the great plugin!
