### ISSUE TITLE
Event motion sensors no longer working

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#5]
**Describe The Bug:**

Following the 1.0.4 update, the event motion sensors stopped working. I downgraded to 1.0.3 (and 1.0.2) but they still don't work (have since re-updated to 1.0.4).

**Environment:**

* **Plugin Version**: 1.0.4
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 18.14.2
* **NPM Version**: 9.5.0
* **Operating System**: Raspbian

**Comment by adhyh** [comment]
Hi Arthur,

Do you see this with all events, or just some in particular? From your previous issue I see you only had statusNotSafe event in your config. 

The way statusNotSafe is currently implemented it only triggers the event when the car has been on the move and then parked in an unsafe condition for a few minutes. So it will not trigger if the car hasn't moved. I will make statusNotSafe more robust in the next update.

If this is not the issue, please let me know which events don't work an I will take a look.

**Comment by r2shyyou** [comment]
I currently have the following in my config:

                 "eventMotionSensors": [
                    {
                        "event": "statusNotSafe",
                        "name": "Car Unsafe State"
                    },
                    {
                        "event": "parked",
                        "name": "Car is Parked"
                    },
                    {
                        "event": "notParked",
                        "name": "Car is Moving"
                    },
                    {
                        "event": "chargingStarted",
                        "name": "Charging Started"
                    },
                    {
                        "event": "chargingStopped",
                        "name": "Charging Stopped"
                    },
                    {
                        "event": "climatisationStarted",
                        "name": "Car Climate Control Started"
                    }
                ]

I haven't tried charging since noticing that these stopped working so I can't say for sure if the charging sensors do or don't work but I can say the "parked", "notParked", and "climatisationStarted" sensors are no longer working.

Additionally, I noticed that the Location motion sensors have also stopped working. Should I open a separate bug for that or just keep both issues here?

**Comment by r2shyyou** [comment]
i can confirm the event motion sensors are now working. thanks!
