### ISSUE TITLE
Add remaining mileage/kms as an accessory

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#7]
**Describe the solution you'd like:**
Add remaining mileage/kms as an accessory (e.g. light, thermostat, not sure what would be best)

**Comment by adhyh** [comment]
I thought about this before, but there is not really a suitable accessory to show mileage. What I can do is make a lightbulb with the percentage being the remaining km's. Obviously it is limited to <= 100 km, but that should be sufficient for most usecases. What do you think?

**Comment by r2shyyou** [comment]
> I thought about this before, but there is not really a suitable accessory to show mileage. What I can do is make a lightbulb with the percentage being the remaining km's. Obviously it is limited to <= 100 km, but that should be sufficient for most usecases. What do you think?

is it possible to define the scale/number of speeds for a fan service? perhaps that could be used (obviously a fan with 300+ speeds isn't realistic but if it's doable, it could be an idea worth checking out).

i agree that there isn't really a suitable accessory...

as for a lightbulb with remaining kms <= 100, it might be the only option, if the above fan idea isn't possible, but i personally don't know that i'd find it useful, seeing as you've already added battery percentage, but i can say it'd be interesting to play around with.

**Comment by adhyh** [comment]
fan service unfortunately is also a percentage with no decimals. 

But the currentTemperature service does have decimals, so 466 remaining km's could be presented as 46.6 degrees. I will play around a bit and see what works best..

**Comment by r2shyyou** [comment]
> fan service unfortunately is also a percentage with no decimals.
> 
> But the currentTemperature service does have decimals, so 466 remaining km's could be presented as 46.6 degrees. I will play around a bit and see what works best..

ooh, how about a light/luminosity sensor? that can go from 0 to tens of thousands

**Comment by adhyh** [comment]
You're right! That's the best option I guess..

**Comment by adhyh** [comment]
I implemented both your suggestions. The light sensor works well it seems. I will test it a bit more before releasing the new version to avoid messing up existing setups.

**Comment by r2shyyou** [comment]
> I implemented both your suggestions. The light sensor works well it seems. I will test it a bit more before releasing the new version to avoid messing up existing setups.

excellent, thanks!

**Comment by adhyh** [comment]
done, with some additional cool features. See [https://github.com/adhyh/homebridge-vwconnectid#changelog](url)

**Comment by r2shyyou** [comment]
update hasn't yet show up, but thanks!!

**Comment by adhyh** [comment]
New version is published now.

**Comment by r2shyyou** [comment]
> New version is published now.

i see it and have updated but do t see any change...

**Comment by adhyh** [comment]
Did you update the configuration according to the readme and restart homebridge?

- locationMotionSensors -> destinations block
- remainingRangeAccessory
- 'locked' eventMotionSensor

Also remember that new accessories are not automatically placed in your car 'room' but in a standard room. Also, did you see new accessories created in the log?

**Comment by adhyh** [comment]
hmm. it seems like there still is an issue. Maybe better to downgrade to the previous version until it is solved. 

Unfortunately it's just you and me who are giving feedback on the performance so quite hard to thoroughly test..

**Comment by adhyh** [comment]
OK, sorry for the confusion. version 1.1.1 is published and should be working well, with all the new features.

**Comment by r2shyyou** [comment]
indeed, difficult to test with just 2 people! all looks great now though, thanks!

oh, and small correction: in your sample config, you're missing the quote character before the colon

`"remainingRangeAccessory: "Remaining km",`

thanks again though, looks great!
