### ISSUE TITLE
Add locked/unlocked state

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#8]
**Describe the solution you'd like:**
Add locked/unlocked state, even if only informational (since, as previously confirmed, it's not possible to lock/unlock from the app)

**Comment by adhyh** [comment]
Sure, I can add a lockStateChange motion sensor event to the next update.

**Comment by adhyh** [comment]
done, with some additional cool features. See [https://github.com/adhyh/homebridge-vwconnectid#changelog](url)
